### ISSUE TITLE
3D version of clDice Loss

### ISSUE THREAD

**Issue by WonderSimiliar** [jacobkoenig/clDice-Loss#1]
Hi，jacobkoenig
I am very glad to see your excelent work clDice.
I simplely modified it into 3D version(like con2d-->con3d, stride(1,1)-->stride(1,1,1)), but it did not work in my 3D vessel-like dataset.
Could you please give me some advices to implement the 3D version of clDice?
Thanks!

**Comment by jocpae** [comment]
Dear community, after acceptance in CVPR 2021 we now offer an official 2D and 3D implementation of cldice at https://github.com/jocpae/clDice . Thanks a lot to @jacobkoenig  for implementing cldice :)
